# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse500(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, status: int=None, timestamp: str=None, url: str=None, exec_info: str=None):  # noqa: E501
        """InlineResponse500 - a model defined in Swagger

        :param status: The status of this InlineResponse500.  # noqa: E501
        :type status: int
        :param timestamp: The timestamp of this InlineResponse500.  # noqa: E501
        :type timestamp: str
        :param url: The url of this InlineResponse500.  # noqa: E501
        :type url: str
        :param exec_info: The exec_info of this InlineResponse500.  # noqa: E501
        :type exec_info: str
        """
        self.swagger_types = {
            'status': int,
            'timestamp': str,
            'url': str,
            'exec_info': str
        }

        self.attribute_map = {
            'status': 'status',
            'timestamp': 'timestamp',
            'url': 'url',
            'exec_info': 'exec_info'
        }

        self._status = status
        self._timestamp = timestamp
        self._url = url
        self._exec_info = exec_info

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse500':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_500 of this InlineResponse500.  # noqa: E501
        :rtype: InlineResponse500
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> int:
        """Gets the status of this InlineResponse500.


        :return: The status of this InlineResponse500.
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status: int):
        """Sets the status of this InlineResponse500.


        :param status: The status of this InlineResponse500.
        :type status: int
        """

        self._status = status

    @property
    def timestamp(self) -> str:
        """Gets the timestamp of this InlineResponse500.


        :return: The timestamp of this InlineResponse500.
        :rtype: str
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: str):
        """Sets the timestamp of this InlineResponse500.


        :param timestamp: The timestamp of this InlineResponse500.
        :type timestamp: str
        """

        self._timestamp = timestamp

    @property
    def url(self) -> str:
        """Gets the url of this InlineResponse500.


        :return: The url of this InlineResponse500.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this InlineResponse500.


        :param url: The url of this InlineResponse500.
        :type url: str
        """

        self._url = url

    @property
    def exec_info(self) -> str:
        """Gets the exec_info of this InlineResponse500.


        :return: The exec_info of this InlineResponse500.
        :rtype: str
        """
        return self._exec_info

    @exec_info.setter
    def exec_info(self, exec_info: str):
        """Sets the exec_info of this InlineResponse500.


        :param exec_info: The exec_info of this InlineResponse500.
        :type exec_info: str
        """

        self._exec_info = exec_info
